### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by kareniel** [kareniel/diacritic-menu#1]
- [ ] write objective-c++ (appkit) implementation of `sendKey()`
- [ ] write interface to sendKey in C++ code
- [ ] write C++ Node.js Addon
- [ ] invoke `sendKey()` in Electron
- [ ] write rest of app in Electron

---

- [ ] port `sendKey()` to Windows
- [ ] port `sendKey()` to Lnux
